### ISSUE TITLE
Not reading CAN bus after solidering

### ISSUE THREAD

**Issue by MBS212** [adafruit/Adafruit-RP2040-CAN-Bus-Feather-PCB#1]
Hi, all.

If anyone have more experience with this board.

I have an issue came out with this board after I soldered the pcb terminals to it (see the pics attached).

Before it was reading the bus very well and did not have any problems.

Also, can anyone explain better which pins I can connect my devices (relays, servos, ...) to the board, and to which I must not connect if I want the board's CAN bus read and write to work correctly?

I have the pin 5 connected that controls the servo, and the CAN H, CAN L. 
Nothing else is connected.

When I try
if( mcp.parsePacket() ) 
{
  Serial.println("Inside mcp parse");
}

Serial displays nothing at all. 

thank you. 

![2024-03-21-pico-ready-front](https://github.com/adafruit/Adafruit-RP2040-CAN-Bus-Feather-PCB/assets/163756197/510efbf0-fc5f-4065-a122-0d68aa6ecd3a)
![2024-03-21-pico-ready-back](https://github.com/adafruit/Adafruit-RP2040-CAN-Bus-Feather-PCB/assets/163756197/ac27e0d6-8d84-44a9-95cd-d1a267eaa879)

**Comment by caternuson** [comment]
For tech support, please post in the forums:
https://forums.adafruit.com/
